package guichanger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author profgreg
 */
public class frmMain extends javax.swing.JFrame {

    /**
     * Creates new form frmMain
     */
    public frmMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbGrpGender = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        pwdUser = new javax.swing.JPasswordField();
        btnShow = new javax.swing.JButton();
        btnPwd = new javax.swing.JButton();
        lblChanged = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        cbEmails = new javax.swing.JCheckBox();
        rbMale = new javax.swing.JRadioButton();
        rbFemale = new javax.swing.JRadioButton();
        lblCheckBox = new javax.swing.JLabel();
        lblRadioButton = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        cmbStates = new javax.swing.JComboBox();
        btnCombo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstState = new javax.swing.JList();
        btnState = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("User Name:");
        jLabel1.setName("lblUserName"); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 15, -1, -1));

        jTextField1.setName("txtUserName"); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 12, 82, -1));
        jPanel1.add(pwdUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 11, 90, -1));

        btnShow.setText("Hide/Show");
        btnShow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnShowMouseClicked(evt);
            }
        });
        jPanel1.add(btnShow, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, -1, -1));

        btnPwd.setText("Show Pass");
        btnPwd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPwdMouseClicked(evt);
            }
        });
        jPanel1.add(btnPwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 51, -1, -1));

        lblChanged.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblChanged.setName(""); // NOI18N
        lblChanged.setVisible(false);
        jPanel1.add(lblChanged, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 101, 90, 20));

        jButton2.setText("Close");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 98, -1, -1));

        cbEmails.setText("Receive Emails");
        cbEmails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbEmailsMouseClicked(evt);
            }
        });
        jPanel1.add(cbEmails, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 139, -1, -1));

        rbGrpGender.add(rbMale);
        rbMale.setSelected(true);
        rbMale.setText("Male");
        rbMale.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbMaleMouseClicked(evt);
            }
        });
        jPanel1.add(rbMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        rbGrpGender.add(rbFemale);
        rbFemale.setText("Female");
        jPanel1.add(rbFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        lblCheckBox.setText("jLabel2");
        jPanel1.add(lblCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 143, 130, -1));

        lblRadioButton.setText("jLabel2");
        jPanel1.add(lblRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 184, -1, -1));

        jButton3.setText("jButton3");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 210, -1, -1));

        cmbStates.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CO", "TX", "UT", "WY" }));
        jPanel1.add(cmbStates, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 70, -1));

        btnCombo.setText("ComboBox");
        btnCombo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnComboMouseClicked(evt);
            }
        });
        jPanel1.add(btnCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, -1, -1));

        lstState.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "CO", "TX", "UT", "WY" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lstState.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstState.setSelectedIndex(0);
        jScrollPane1.setViewportView(lstState);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, 80, 60));

        btnState.setText("List");
        btnState.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnStateMouseClicked(evt);
            }
        });
        jPanel1.add(btnState, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnShowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnShowMouseClicked
        if (lblChanged.isVisible())
        {
            lblChanged.setVisible(false);
        }
        else
        {
            lblChanged.setVisible(true);
        }
    }//GEN-LAST:event_btnShowMouseClicked

    private void btnPwdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPwdMouseClicked
        lblChanged.setText(String.valueOf(pwdUser.getPassword()));
    }//GEN-LAST:event_btnPwdMouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jButton2MouseClicked

    private void cbEmailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbEmailsMouseClicked
        if (cbEmails.isSelected())
            lblCheckBox.setText("Send Email");
        else
            lblCheckBox.setText("Don't Send email");
    }//GEN-LAST:event_cbEmailsMouseClicked

    private void rbMaleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbMaleMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_rbMaleMouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        if (rbMale.isSelected())
            lblRadioButton.setText("Male");
        else if (rbFemale.isSelected())
            lblRadioButton.setText("Female");
        else
            lblRadioButton.setText("");
    }//GEN-LAST:event_jButton3MouseClicked

    private void btnComboMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnComboMouseClicked
        String sValue = "";
        
        if (((String)cmbStates.getSelectedItem()).equalsIgnoreCase("co"))
            btnCombo.setText("Colorado");
        else if (((String)cmbStates.getSelectedItem()).equalsIgnoreCase("tx"))
            btnCombo.setText("Texas");
        else if (((String)cmbStates.getSelectedItem()).equalsIgnoreCase("ut"))
            btnCombo.setText("Utah");
        else if (((String)cmbStates.getSelectedItem()).equalsIgnoreCase("wy"))
            btnCombo.setText("Wyoming");
    }//GEN-LAST:event_btnComboMouseClicked

    private void btnStateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStateMouseClicked
        btnState.setText((String)lstState.getSelectedValue());
    }//GEN-LAST:event_btnStateMouseClicked

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCombo;
    private javax.swing.JButton btnPwd;
    private javax.swing.JButton btnShow;
    private javax.swing.JButton btnState;
    private javax.swing.JCheckBox cbEmails;
    private javax.swing.JComboBox cmbStates;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblChanged;
    private javax.swing.JLabel lblCheckBox;
    private javax.swing.JLabel lblRadioButton;
    private javax.swing.JList lstState;
    private javax.swing.JPasswordField pwdUser;
    private javax.swing.JRadioButton rbFemale;
    private javax.swing.ButtonGroup rbGrpGender;
    private javax.swing.JRadioButton rbMale;
    // End of variables declaration//GEN-END:variables
}
