/*
 * Levi Bowser
 * HW 6 - Love Calculator
 * 3.7.15
 */

/**
 *
 * @author Wyatt
 */
public class frmMain extends javax.swing.JFrame {

    /**
     * Creates new form frmMain
     */
    public frmMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBody = new javax.swing.JPanel();
        pnlTop = new javax.swing.JPanel();
        btnClose = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtYourName = new javax.swing.JTextField();
        txtTheirName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnCalculate = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        lblResult = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnClose.setText("Close");
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnCloseMouseReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jLabel3.setText("Love Calculator");

        javax.swing.GroupLayout pnlTopLayout = new javax.swing.GroupLayout(pnlTop);
        pnlTop.setLayout(pnlTopLayout);
        pnlTopLayout.setHorizontalGroup(
            pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTopLayout.createSequentialGroup()
                .addContainerGap(196, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(128, 128, 128)
                .addComponent(btnClose)
                .addGap(18, 18, 18))
        );
        pnlTopLayout.setVerticalGroup(
            pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTopLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addGroup(pnlTopLayout.createSequentialGroup()
                        .addComponent(btnClose)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        txtYourName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtYourNameActionPerformed(evt);
            }
        });

        txtTheirName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTheirNameActionPerformed(evt);
            }
        });

        jLabel1.setText("Your Name:");

        jLabel2.setText("Their Name:");

        btnCalculate.setText("Calculate");
        btnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel4.setText("Result:");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblResult.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout pnlBodyLayout = new javax.swing.GroupLayout(pnlBody);
        pnlBody.setLayout(pnlBodyLayout);
        pnlBodyLayout.setHorizontalGroup(
            pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBodyLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCalculate)
                .addGap(68, 68, 68))
            .addGroup(pnlBodyLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addGroup(pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTheirName, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                    .addComponent(txtYourName)
                    .addComponent(lblResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlBodyLayout.setVerticalGroup(
            pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBodyLayout.createSequentialGroup()
                .addComponent(pnlTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtYourName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(3, 3, 3)
                .addComponent(btnCalculate)
                .addGap(3, 3, 3)
                .addGroup(pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTheirName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(78, 78, 78)
                .addGroup(pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 86, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlBody, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBody, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTheirNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTheirNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTheirNameActionPerformed

    private void btnCloseMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseReleased
        System.exit(0); //this is when the button is realeased to close. that way if you didnt mean to you can still hold down the button and itwont close on ya.
    }//GEN-LAST:event_btnCloseMouseReleased

    private void txtYourNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtYourNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtYourNameActionPerformed

    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed
        
        //^^ the above is for when the caluclate button is clicked.
        int iLove = 0; //da looooooove counter ;D
        
        for (int iCount = 0; iCount < txtYourName.getText().length(); iCount++) 
            { //to count through each letter only to the length of the length of each input
                
                char cLetter;
                cLetter = txtYourName.getText().charAt(iCount); //selects a character at the certain location
                
                switch(cLetter) //specific letter chosen is then compared to each one of the cases
                {
                    case 't':
                        iLove++; //when a letter is matched for lower case it adds one ot love counter
                        break;
                    case 'r':
                        iLove++;
                        break;
                    case 'u':
                        iLove++;
                        break;
                    case 'l':
                        iLove++; // wooooo letter checking
                        break;
                    case 'o':
                        iLove++;
                        break;
                    case 'v':
                        iLove++;
                        break;
                    case 'e': //since there are two e's in TRUELOVE i just made the love counter
                        iLove++;//increment twice instead of trying to make something more difficult
                        iLove++;
                        break;
                    case 'T':
                        iLove++; //when a letter is matched for upper case it adds one ot love counter
                        break;
                    case 'R':
                        iLove++;
                        break;
                    case 'U':
                        iLove++;
                        break;
                    case 'L':
                        iLove++; //a continuation of the letter checking.
                        break;
                    case 'O':
                        iLove++;
                        break;
                    case 'V':
                        iLove++;
                        break;
                    case 'E': //with the double E, i had to make sure to increment twice.
                        iLove++; //no reason to make a loop
                        iLove++;//and i couldnt figure out why iLove += 2 wasnt working for me
                        break;
                        
                    
                                        
                }
            }
        for (int iCount = 0; iCount < txtTheirName.getText().length(); iCount++)//geting length
        {//to count through each letter only to the length of the length of each input
                
                char cLetter;
                cLetter = txtTheirName.getText().charAt(iCount); //this selects each character in each specific spot
                
                switch(cLetter) //its the exact same situation up top
                {
                    case 't':
                        iLove++; //i figure the switch would be the easiest to write and make it go back
                        break;
                    case 'r':
                        iLove++;
                        break;
                    case 'u':
                        iLove++;
                        break;
                    case 'l':
                        iLove++;
                        break;
                    case 'o':
                        iLove++;
                        break;
                    case 'v':
                        iLove++;
                        break;
                    case 'e': //the double increment to make sure that it gets counted properly
                        iLove++;
                        iLove++;
                        break;
                    case 'T':
                        iLove++;
                        break;
                    case 'R':
                        iLove++;
                        break;
                    case 'U':
                        iLove++;
                        break;
                    case 'L':
                        iLove++;
                        break;
                    case 'O':
                        iLove++;
                        break;
                    case 'V':
                        iLove++;
                        break;
                    case 'E':
                        iLove++;
                        iLove++;
                        break;
                                        
                }
        }
        
        
                if(iLove >= 10) //to determine if you are in love! owow!
                {
                    lblResult.setText("You found a match!"); //this is to set the label to a certain text
                }
                else
                {
                    lblResult.setText("Go join a convent");
                }

            
       
        
    }//GEN-LAST:event_btnCalculateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculate;
    private javax.swing.JButton btnClose;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblResult;
    private javax.swing.JPanel pnlBody;
    private javax.swing.JPanel pnlTop;
    private javax.swing.JTextField txtTheirName;
    private javax.swing.JTextField txtYourName;
    // End of variables declaration//GEN-END:variables
}
