/*
 * Levi Bowser
 * Project 2 - GPA Calc and GUI
 * 3.12.15
 */

import java.text.DecimalFormat; //importing the ability to make a decimal format object, bugger to figure out again.

public class GpaCalc extends javax.swing.JFrame {
    

    
    private double CalcClassGPA(double dCredits, String sGrade)
            //this method accepts the parameters for the credits and the grade and calculates
            //the weighted class gpa
            {
                
                
                double dGPA = 0; //initialize variable now to avoid the stupid yellow line
                
                switch(sGrade) //in this case a switch statement seemed for effective and easier to read
                {
                    case "A":
                      dGPA = 4 * dCredits; //i just multiplied the credits straight to the gpa.
                        break;
                    case "A-":
                      dGPA = 3.7 * dCredits; //thanks rodney for the help on this and avoiding 2 extra variables
                        break;
                    case "B+":
                      dGPA = 3.4 * dCredits;
                        break;
                    case "B":
                      dGPA = 3 * dCredits;
                        break;
                    case "B-":
                      dGPA = 2.7 * dCredits; // i included the minus sign in the combo boxes and its recognized them. pleasant suprise to be honest.
                        break;
                    case "C+":
                      dGPA = 2.4 * dCredits;
                        break;
                    case "C":
                      dGPA = 2 * dCredits;
                        break;
                    case "C-":
                      dGPA = 1.7 * dCredits;
                        break;
                    case "D+":
                      dGPA = 1.4 * dCredits;
                        break;
                    case "D":
                      dGPA = 1 * dCredits;
                        break;
                    case "D-":
                      dGPA = .7 * dCredits;
                        break;
                    case "E":
                      dGPA = 0 * dCredits; //i didnt set a default becuase no matter what, one of these was going to be fulfilled.
                        break;
                }
                
                return dGPA; //the resulting gpa is the number given back to the object that called it.
               
            }
    /**
     * Creates new form GpaCalc
     */
    public GpaCalc() {
        initComponents();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtYourName = new javax.swing.JTextField();
        pnlGrades = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtBUSM241 = new javax.swing.JTextField();
        txtIS100 = new javax.swing.JTextField();
        txtIS102 = new javax.swing.JTextField();
        txtIS201 = new javax.swing.JTextField();
        txtIS303 = new javax.swing.JTextField();
        txtACC200 = new javax.swing.JTextField();
        txtFIN201 = new javax.swing.JTextField();
        cboxBUSM241 = new javax.swing.JComboBox();
        cboxIS100 = new javax.swing.JComboBox();
        cboxIS102 = new javax.swing.JComboBox();
        cboxIS201 = new javax.swing.JComboBox();
        cboxIS303 = new javax.swing.JComboBox();
        cboxACC200 = new javax.swing.JComboBox();
        cboxFIN201 = new javax.swing.JComboBox();
        btnCalcGPA = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        pnlGPA = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        txtGPA = new javax.swing.JLabel();
        pnlGreen = new javax.swing.JPanel();
        pnlYellow = new javax.swing.JPanel();
        pnlRed = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("IS Pre-Req GPA Calculator");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 26, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Enter Your Name:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 74, -1, -1));
        jPanel1.add(txtYourName, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 73, 141, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 110));

        pnlGrades.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlGrades.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Enter Grades");
        pnlGrades.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 12, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setText("Course");
        pnlGrades.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel5.setText("Credits");
        pnlGrades.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel6.setText("Grade");
        pnlGrades.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, -1, -1));

        jLabel7.setText("BUSM 241");
        pnlGrades.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, -1, -1));

        jLabel8.setText("IS 100");
        pnlGrades.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        jLabel9.setText("IS 102");
        pnlGrades.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        jLabel10.setText("IS 201");
        pnlGrades.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        jLabel11.setText("IS 303");
        pnlGrades.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        jLabel12.setText("ACC 200");
        pnlGrades.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));

        jLabel13.setText("FIN 201");
        pnlGrades.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, -1));

        txtBUSM241.setText("3");
        pnlGrades.add(txtBUSM241, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 30, -1));

        txtIS100.setText(".5");
        pnlGrades.add(txtIS100, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 30, -1));

        txtIS102.setText(".5");
        pnlGrades.add(txtIS102, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 30, -1));

        txtIS201.setText("3");
        pnlGrades.add(txtIS201, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 30, -1));

        txtIS303.setText("3");
        pnlGrades.add(txtIS303, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 30, -1));

        txtACC200.setText("3");
        pnlGrades.add(txtACC200, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 30, -1));

        txtFIN201.setText("3");
        pnlGrades.add(txtFIN201, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 30, -1));

        cboxBUSM241.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "D-", "E" }));
        pnlGrades.add(cboxBUSM241, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, -1, -1));

        cboxIS100.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "D-", "E" }));
        pnlGrades.add(cboxIS100, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, -1, -1));

        cboxIS102.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "D-", "E" }));
        pnlGrades.add(cboxIS102, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, -1, -1));

        cboxIS201.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "D-", "E" }));
        pnlGrades.add(cboxIS201, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, -1, -1));

        cboxIS303.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "D-", "E" }));
        pnlGrades.add(cboxIS303, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, -1, -1));

        cboxACC200.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "D-", "E" }));
        pnlGrades.add(cboxACC200, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, -1, -1));

        cboxFIN201.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "D-", "E" }));
        pnlGrades.add(cboxFIN201, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, -1, -1));

        btnCalcGPA.setText("Calc GPA");
        btnCalcGPA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCalcGPAMouseClicked(evt);
            }
        });
        pnlGrades.add(btnCalcGPA, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, -1, -1));

        btnReset.setText("Reset");
        btnReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnResetMouseClicked(evt);
            }
        });
        pnlGrades.add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, -1, -1));

        getContentPane().add(pnlGrades, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 320, 410));

        pnlGPA.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlGPA.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel14.setText("GPA");
        pnlGPA.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        txtGPA.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        pnlGPA.add(txtGPA, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 60, 20));

        pnlGreen.setBackground(new java.awt.Color(102, 255, 0));
        pnlGreen.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlGreen.setVisible(false);
        pnlGPA.add(pnlGreen, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 40, 40));

        pnlYellow.setBackground(new java.awt.Color(255, 255, 0));
        pnlYellow.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlYellow.setVisible(false);
        pnlGPA.add(pnlYellow, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 40, 40));

        pnlRed.setBackground(new java.awt.Color(255, 0, 0));
        pnlRed.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlRed.setVisible(false);
        pnlGPA.add(pnlRed, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 40, 40));

        getContentPane().add(pnlGPA, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 190, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcGPAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCalcGPAMouseClicked
    //the event for mouse click for the calcgpa button
        
    DecimalFormat dfGPA = new DecimalFormat("0.00"); //setting the format for the object method to format the gpa.
    
    double dIS100Cred = Double.parseDouble(txtIS100.getText()); //i set the variables to make adding the total credits easier.
    double dIS102Cred = Double.parseDouble(txtIS102.getText());// i used the parse double to change the string from the txt fields
    double dIS201Cred = Double.parseDouble(txtIS201.getText());// where the number of credits are put in to make sure to be
    double dIS303Cred = Double.parseDouble(txtIS303.getText());//able to use math lower down when adding them together.
    double dACC200Cred = Double.parseDouble(txtACC200.getText());//i made sure to call the parsedouble method, then the get text
    double dFIN201Cred = Double.parseDouble(txtFIN201.getText());//method to make sure i grabbed the correct value from each.
    double dBUSM241Cred = Double.parseDouble(txtBUSM241.getText());
    
    double dTotalCredits =  dIS100Cred + dIS102Cred + dIS201Cred + dIS303Cred + dACC200Cred + dFIN201Cred + dBUSM241Cred; //adding all the variable together for the total number of credits.
    
    double dIS100GPA = CalcClassGPA(Double.parseDouble(txtIS100.getText()), String.valueOf(cboxIS100.getSelectedItem())); //get class weighted avg for each class.
    double dIS102GPA = CalcClassGPA(Double.parseDouble(txtIS102.getText()), String.valueOf(cboxIS102.getSelectedItem()));// this is calling the method i made previously (CalcClassGPA()) to get each
    double dIS201GPA = CalcClassGPA(Double.parseDouble(txtIS201.getText()), String.valueOf(cboxIS201.getSelectedItem()));//classes waited gpa. it made it easier creating one method and referencing
    double dIS303GPA = CalcClassGPA(Double.parseDouble(txtIS303.getText()), String.valueOf(cboxIS303.getSelectedItem()));//to the method to save code and space.
    double dACC200GPA = CalcClassGPA(Double.parseDouble(txtACC200.getText()), String.valueOf(cboxACC200.getSelectedItem()));//the string.valueOf gets the string originally in the txt fields and converts
    double dFIN201GPA = CalcClassGPA(Double.parseDouble(txtFIN201.getText()), String.valueOf(cboxFIN201.getSelectedItem()));//them into a string. thanks java for that code.
    double dBUSM241GPA = CalcClassGPA(Double.parseDouble(txtBUSM241.getText()), String.valueOf(cboxBUSM241.getSelectedItem()));// gave varaible to easily add up the total weighted gpa below
    
    double dTotalWeightGPA = dIS100GPA + dIS102GPA + dIS201GPA + dIS303GPA + dACC200GPA + dFIN201GPA + dBUSM241GPA; //getting the total number of gpas to soon calculate the avg.
    
    double dGPA = dTotalWeightGPA / dTotalCredits; //getting the average gpa all together using the number of total number of gpa divided by the credits for weight.
      
    txtGPA.setText(String.valueOf(dfGPA.format(dGPA))); //calling the object and its class to format the gpa. and then setting the result as the diplay for the txt box meant to display gpa.
    
    if(dGPA >= 3.7) //this is to choose whichever colored panel should appear.
    {
        pnlGreen.setVisible(true);//true allows the panal to be visible
        pnlYellow.setVisible(false); //while false makes sure its invisible.
        pnlRed.setVisible(false);//initially i made each panal = .setVisible(false); in the custom code menu.       
    }
    else if (dGPA >= 3.2) //if its lower than 3.7 but higher than 3.2 i made sure that yellow popped up.
    {
        pnlGreen.setVisible(false);
        pnlYellow.setVisible(true);
        pnlRed.setVisible(false);
    }
    else //and if the other two condidtions werent fulfilled i set it to make red appear.
    {
        pnlGreen.setVisible(false);
        pnlYellow.setVisible(false);
        pnlRed.setVisible(true);
    }
    
    }//GEN-LAST:event_btnCalcGPAMouseClicked

    private void btnResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResetMouseClicked
       //button click for the reset button
        
        //this is to make sure all values go back to the orginal state so its a "reset." go figure.
        
    cboxIS100.setSelectedIndex(0); //i made each combo box set itself to the value
    cboxIS102.setSelectedIndex(0);//that was at the very first entry in the models
    cboxIS201.setSelectedIndex(0);//it has to be at 0 becuase 0 is the start of everything.
    cboxIS303.setSelectedIndex(0);// i think its becuase combo boxs are a type of string object.
    cboxFIN201.setSelectedIndex(0);// not sure.
    cboxACC200.setSelectedIndex(0);
    cboxBUSM241.setSelectedIndex(0);
    
    pnlGreen.setVisible(false);
    pnlYellow.setVisible(false); //making to reset the colored panels invisible in case they appeared from previous entries.
    pnlRed.setVisible(false);
       
    txtGPA.setText("0.00"); //resetting the gpa text from previous use.
    
    txtYourName.setText(null); //erasing everything in the text where your name was input
    txtYourName.requestFocus(); //gets the cursor to the txt where you put your name 
    
        
    }//GEN-LAST:event_btnResetMouseClicked
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
    
    
    
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GpaCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GpaCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GpaCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GpaCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GpaCalc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcGPA;
    private javax.swing.JButton btnReset;
    private javax.swing.JComboBox cboxACC200;
    private javax.swing.JComboBox cboxBUSM241;
    private javax.swing.JComboBox cboxFIN201;
    private javax.swing.JComboBox cboxIS100;
    private javax.swing.JComboBox cboxIS102;
    private javax.swing.JComboBox cboxIS201;
    private javax.swing.JComboBox cboxIS303;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel pnlGPA;
    private javax.swing.JPanel pnlGrades;
    private javax.swing.JPanel pnlGreen;
    private javax.swing.JPanel pnlRed;
    private javax.swing.JPanel pnlYellow;
    private javax.swing.JTextField txtACC200;
    private javax.swing.JTextField txtBUSM241;
    private javax.swing.JTextField txtFIN201;
    private javax.swing.JLabel txtGPA;
    private javax.swing.JTextField txtIS100;
    private javax.swing.JTextField txtIS102;
    private javax.swing.JTextField txtIS201;
    private javax.swing.JTextField txtIS303;
    private javax.swing.JTextField txtYourName;
    // End of variables declaration//GEN-END:variables

    

   
    
}
